# Generated by Django 3.0.4 on 2020-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_ID', models.IntegerField()),
                ('Emp_Name', models.CharField(max_length=64)),
                ('Experience', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Address', models.CharField(max_length=256)),
                ('Tech_Skills', models.CharField(max_length=256)),
            ],
        ),
    ]
